src/Entity/Formation.php
<?php

namespace App\Entity;


use App\Repository\FormationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Null_;

/**
 * @ORM\Entity(repositoryClass=FormationRepository::class)
 */
class Formation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $duree;

    /**
     * @ORM\Column(type="date")
     */
    private $begin_at;

    /**
     * @ORM\Column(type="string",length=255)
     */
    private $image;


    /**
     * @ORM\OneToMany(targetEntity=Participant::class, mappedBy="Formation",cascade={"persist", "remove"})
     */
    private $participants;

    public function __construct()
    {
        $this->participants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getBeginAt(): ?\DateTimeInterface
    {
        return $this->begin_at;
    }

    public function setBeginAt(\DateTimeInterface $begin_at): self
    {
        $this->begin_at = $begin_at;

        return $this;
    }

    /**
     * @return Collection<int, Participant>
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(Participant $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
            $participant->setFormation($this);
        }

        return $this;
    }

    public function removeParticipant(Participant $participant): self
    {
        if ($this->participants->removeElement($participant)) {
            // set the owning side to null (unless already changed)
            if ($participant->getFormation() === $this) {
                $participant->setFormation(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param mixed $image
     */
    public function setImage($image): void
    {
        $this->image=$image;
    }

}

src/Form/FormationType.php
<?php

namespace App\Form;

use App\Entity\Formation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
class FormationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('price')
            ->add('duree')
            ->add('begin_at')
            ->add('image',FileType::class,[
                'required' => false,
                'data_class'=>null
            ])
            ->add('Submit',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Formation::class,
        ]);
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;
use App\Entity\Participant;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\HttpFoundation\Request;
use SebastianBergmann\Environment\Console;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Form\FormationType;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Formation;
use Doctrine\ORM\EntityManagerInterface;

 /**
     * @Route("/formation", name="")
     */
class FormationController extends AbstractController
{
    /**
     * @Route("/", name="app_formation")
     */
    public function index(): Response
    {
        $entityManger=$this->getDoctrine()->getManager();
        $formation=new Formation();
        $formation->setTitre('python');
        $formation->setPrice(10.0);
        $formation->setDuree(15);
        $formation->setBeginAt(new \DateTimeImmutable());
        $entityManger->persist($formation);
        $entityManger->flush();

        return $this->render('formation/index.html.twig', [
            'id' => $formation->getId(),
        ]);
    }



        /**
         * @Route("/formation/{id}",name="formation")
         */

    public function show($id)
    {
        $formation = $this->getDoctrine()
        ->getRepository(Formation::class)
        ->find($id);

    if (!$formation) {
        throw $this->createNotFoundException(
            'No formation found for id ' . $id
        );
    }
    $em=$this->getDoctrine()->getManager();
    $participant=$em->getRepository(Participant::class);
    $listParticipant=$em
    ->getRepository(Participant::class)
    ->findBy(['Formation'=>$formation]);
  
    return $this->render('formation/show.html.twig', [

        'formation' => $formation,
        'participant'=>$participant,
        'listParticipant'=>$listParticipant
    ]);

    }
    
     //============Ajouter une formation===============//

    /**
     * @Route("/Ajouter",name="ajouter_formation")
     */
    public function ajouter(Request $request,EntityManagerInterface $entityManger)
    {   $publicPath="uploads/";
        $formation= new Formation();
        $form=$this->createForm(FormationType::class,$formation);
        $form->handleRequest($request);
        if($form->isSubmitted()){
            /**
             * @var UploadedFile $image
             */
            $image=$form->get('image')->getData();
            if($image){
                $imageName=$formation->getTitre().'.'.$image->guessExtension();
                $image->move($publicPath,$imageName);
                $formation->setImage($imageName);
            }

            $entityManger->persist($formation);
            $entityManger->flush();
           
            return $this->redirectToRoute("show");
        }

        return $this->render('formation/ajouter.html.twig',[
            'formation_form'=> $form->createView()
        ]);


    }

     //============Afficher les formations===============//

    /**
     * @Route("/home",name="show")
     */
    public function home(Request $request){
        $em=$this->getDoctrine()->getManager();
        $repo=$em->getRepository(Formation::class);
        $lesFormations=$repo->findAll();
        $publicPath=$request->getScheme().'://'.$request->getHttpHost().$request->getBasePath().'/uploads/';
        return $this->render("formation/home.html.twig",[
            'lesFormations'=>$lesFormations,
            'publicPath'=>$publicPath
        ]);
    }


     //============Effacer une formation===============//

     /**
     *@Route("/delete/{id}",name="formation_delete")
     */
    public function delete(Request $request,$id):Response
    {
        $p=$this->getDoctrine()
            ->getRepository(Formation::class)
            ->find($id);
            if(!$p){
                throw $this->createNotFoundException(
                    'No participant found for id'.$id
                );
            }
            $entityManger=$this->getDoctrine()->getManager();
            $entityManger->remove($p);
            $entityManger->flush();
            return $this->redirectToRoute("show");
    }

     //============Modifier une formation===============//


   /**
     * @Route("/editF/{id}",name="editF")
     * Method({"GET","POST"})
     */
    public function edit(Request $request,$id)
    {
        $publicPath="uploads/";
        $formation=new Formation();

        $formation=$this->getDoctrine()->getRepository(Formation::class)
                          ->find($id);
        if(!$formation){
            throw $this->createNotFoundException(
                'No participant found for id'.$id
            );
        }
        $form=$this->createForm(FormationType::class,$formation);
        $form->handleRequest($request);
        if($form->isSubmitted())
        {
             /**
             * @var UploadedFile $image
             */
            $image=$form->get('image')->getData();
            if($image){
                $imageName=$formation->getTitre().'.'.$image->guessExtension();
                $image->move($publicPath,$imageName);
                $formation->setImage($imageName);
            }
            $entityManger=$this->getDoctrine()->getManager();
            $entityManger->flush();
            return $this->redirectToRoute("show");
        }
        return $this->render('formation/ajouter.html.twig',
        [
            "formation_form"=>$form->createView()
        ]);

    }

}

templates/formation/ajouter.html.twig
{% extends "base.html.twig" %}
{% block title %}
    Ajout Formation
{% endblock %}
{% block body %}
    <h2 class="d-flex justify-content-center mt-5"> Ajouter une formation </h2>
    <div class="d-flex justify-content-center mt-5 ">
    

<div class="card border-info mb-3 " style="max-width: 18rem;">
  <div class="card-header">Ajouter une formation </div>
  <div class="card-body text-info alert alert-info  ">
    {{form_start(formation_form)}}
<div class="input-field border-primary ">
{{form_label(formation_form.titre)}} : 
{{form_widget(formation_form.titre,{'attr':{'placeholder':'Titre de la formation'}})}}
</div>
<div class="input-field">
{{form_label(formation_form.price)}} : 
{{form_widget(formation_form.price,{'attr':{'placeholder':'Prix de la formation'}})}}
</div>
<div class="input-field">
{{form_label(formation_form.duree)}} : 
{{form_widget(formation_form.duree,{'attr':{'placeholder':'Duree de la formation'}})}}
</div>
<div class="input-field ">
{{form_label(formation_form.begin_at)}} : 
{{form_widget(formation_form.begin_at,{'attr':{'placeholder':'Debut de la formation'}})}}
</div>
<div class="input-field ">
{{form_label(formation_form.image)}} : 
{{form_widget(formation_form.image,{'attr':{'placeholder':'image de la formation'}})}}
</div>


<div class="ml-5">
 {{form_widget(formation_form.Submit)}}
</div>
   
  </div>
</div>
{{form_end(formation_form)}}


</div>
{% endblock %} 

templates/formation/home.html.twig
{% extends 'base.html.twig' %}
{% block body %}
	<h1 class="d-flex justify-content-center mt-5 mb-5">Liste des formations</h1>

	<table class="table table-hover table-striped" border="1">
		<thead class="bg-info">
			<tr>
				<th>#</th>
				<th>Titre
				</th>
				<th>Begin_at</th>
				<th>Duree</th>
				<th>Price</th>
				<th>Image</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody class="table-light">
			{% for formation in lesFormations %}
				<tr>
					<td>{{formation.id}}</td>
					<td>{{formation.titre |upper}}</td>
					<td>{{formation.beginAt |date('d/m/y')}}</td>
					<td>{{formation.duree}}</td>
					<td>{{formation.price}}</td>
					{% if formation.image is not empty %}
					<td><img class="w-25" src="{{publicPath~formation.image}}"/></td>
					{% else %}
					<td>Cette formation n'a pas d'image.</td>
					{% endif %}
					
					
					<td>
						<a class="btn btn-info" href="{{path('editF',{'id':formation.id})}}">Modifier</a>
						<a class="btn btn-danger" href="{{path('formation_delete',{'id':formation.id})}}">Supprimer</a>
						
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="5">Aucun abonné</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/formation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FormationController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
   <h1>ajout du formation avec succé num {{id}}</h1>
</div>
{% endblock %}

templates/formation/show.html.twig
{% extends "base.html.twig" %}
{% block title %}{{parent()}} - Edit {% endblock %}
{% block titre %}{{parent()|upper}} - consultation de {{formation.getTitre()}} {% endblock %}
{% block body %}

<h1> le nom du formation est {{formation.getTitre()}} </h1>
<h1> le prix du formation est {{formation.getPrice()}} </h1>
<h1> le prix du formation est {{formation.getDuree()}} </h1>
<h2> Date de debut {{formation.getBeginAt()| date('d-m-y')}} </h2>



{% endblock %}